// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsoMFQ62timbKAAngxf0b9RUOrnSdzcvg',
    appId: '1:640269433885:web:ab28593fc884421f249af4',
    messagingSenderId: '640269433885',
    projectId: 'addictiontracker-2f028',
    authDomain: 'addictiontracker-2f028.firebaseapp.com',
    storageBucket: 'addictiontracker-2f028.appspot.com',
    measurementId: 'G-952SYHGJF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKt1eAuhdfLMmImpEF8Q6K0ec1Z37C-ZI',
    appId: '1:640269433885:android:1f1a46e250ac6643249af4',
    messagingSenderId: '640269433885',
    projectId: 'addictiontracker-2f028',
    storageBucket: 'addictiontracker-2f028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF2GuKIHnPNWkMgSv2FR6Px10sxJYpWeo',
    appId: '1:640269433885:ios:129a24f9ec7cb211249af4',
    messagingSenderId: '640269433885',
    projectId: 'addictiontracker-2f028',
    storageBucket: 'addictiontracker-2f028.appspot.com',
    iosClientId:
        '640269433885-ogvkjbsnkbdoplr2vlpd2qpam6s38pe9.apps.googleusercontent.com',
    iosBundleId: 'com.jewelexx.addictiontracker',
  );
}
